[package]
name = "qrcodegen"
version = "1.9.0"
edition = "2024"

authors = ["Project Nayuki"]
description = "High-quality QR Code generator library"
homepage = "https://www.nayuki.io/page/qr-code-generator-library"
repository = "https://github.com/nayuki/QR-Code-generator"
keywords = ["qr-code", "barcode", "encoder", "image"]
categories = ["encoding", "multimedia::images"]
license = "MIT"
exclude = ["examples/*"]

[dependencies]
image = { version = "0.25", default-features = false, optional = true }
encoding-next-index-japanese = { version = "1.20180106.0", default-features = false, optional = true }

[lints]
clippy.bool_assert_comparison = "allow"
clippy.items_after_test_module = "allow"
